### PR TITLE
fix: insert with unsigned data return out of range, but still being queried #1218

### LINKED ISSUE #1218: bug: insert into UNSIGNED data out of range return error, but can be quried
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```shell
mysql> create table int_test (id int unsigned);
Query OK, 0 rows affected (0.00 sec)

mysql> insert into int_test values(2147483648);
ERROR 1264 (22003): Out of range[0, 2147483647] for column 'id' value: 2147483648

mysql> select * from int_test;
+------------+
| id         |
+------------+
| 2147483648 |
+------------+
1 row in set (0.00 sec)
```
`tinyint smallint mediumint bigint`  also have this problem.

### Expected behavior

_No response_

### How To Reproduce

```sql
create table int_test (id int unsigned);
insert into int_test values(2147483648);
select * from int_test;
```

### Environment

```shell
root@ub01:~# /stonedb57/install/bin/mysqld --version
/stonedb57/install/bin/mysqld  Ver 5.7.36-StoneDB for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: 1fa9d3346
        Last commit time: Date:   Fri Jan 13 07:03:20 2023 +0000
        Build time: Date: Fri Jan 13 17:22:15 CST 2023
root@ub01:~# cat /etc/issue
Ubuntu 20.04.5 LTS \n \l
```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

### PR DESCRIPTION
**Pull request by hustjieke**
## Summary about this PR

1. Fix int signed & unsigned: -2147483648 and [2147483648, 4294967295] is not allowed.
2. Fix bigint signed & unsigned: -9223372036854775808 and [9223372036854775808, 18446744073709551615] is not allowed.
3. Like int&bigint, fix unsigned [tinyint, smallint, mediumint] unsupported values except negative data.

Issue Number: close #1218

## Tests Check List

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [x] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Comment by hustjieke** [comment]
Please make a CR, ping @isredstar @RingsC @lujiashun @wisehead

**Review by wisehead — APPROVED** [review]

File: storage/tianmu/common/common_definitions.cpp [hunk 1]
```diff
@@ -34,52 +34,64 @@ void PushWarning(THD *thd, Sql_condition::enum_severity_level level, uint code,
...
+// We use std::exception() but not commong::Exceptions here as it will raise infos like "internal error in storage
+// tianmu ..." on mysql client, this is not user friendly. Users has already get error msg from push_warning() func.
 void PushWarningIfOutOfRange(THD *thd, std::string col_name, int64_t v, int type, bool unsigned_flag) {
   // below `0` is for min unsigned value.
   switch (type) {
     case 1: {  // MYSQL_TYPE_TINY
       if (unsigned_flag && (static_cast<uint64_t>(v) > TIANMU_TINYINT_MAX)) {
         PushWarning(thd, Sql_condition::SL_WARNING, ER_WARN_DATA_OUT_OF_RANGE,
                     getErrMsg(col_name, 0, TIANMU_TINYINT_MAX, unsigned_flag, v).c_str());
+        throw std::exception();
```
Comment (RingsC) [inline storage/tianmu/common/common_definitions.cpp:46]: The std::exception is not the best choice, we can throw a specific exception. For example: DataTypeNotSupported or something related.
The some reseaon for that:
1: The exception is the base class, we should not throw that as our first choice; 
2: The eeception mechanism is havery-cost way;
3: The catch statement will be taken more statements to catch this.

**Review by lujiashun — APPROVED** [review]
LGTM

**Review by RingsC — CHANGES_REQUESTED** [review]
