### PR TITLE
fix(tianmu): fix Trigger with primary key which assigns value selected (#581)

### LINKED ISSUE #581: bug: incorrect result set,Trigger with primary key which assigns value selected from table to field of row,being inserted/updated.Test results are wrong
### Describe the problem

```
create table t1 (id int primary key, copy int)engine=tianmu;
create table t2 (id int primary key, data int)engine=tianmu;
insert into t2 values (1,1), (2,2);
create trigger t1_bi before insert on t1 for each row
  set new.copy= (select data from t2 where id = new.id);
create trigger t1_bu before update on t1 for each row
  set new.copy= (select data from t2 where id = new.id);
insert into t1 values (1,3), (2,4), (3,3);
update t1 set copy= 1 where id = 2;
select * from t1;

### Incorrect test results ###
+----+------+
| id | copy |
+----+------+
|  1 | NULL |
|  2 | NULL |
|  3 | NULL |
+----+------+

drop table t1, t2;
```

### Expected behavior

```
#Correct test results（note:Innodb test verification, test results are as follows）
select * from t1;
+----+------+
| id | copy |
+----+------+
|  1 |    1 |
|  2 |    2 |
|  3 | NULL |
+----+------+
```

### How To Reproduce

```
Follow the test steps above
```

### Environment

```
./mysqld  Ver 5.7.36_v1.0.1_beta-StoneDB for Linux on x86_64 (build-)
build information as follow: 
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: 208f79d
        Last commit time: Date:   Sat Sep 17 16:19:42 2022 +0800
        Build time: Date: Sat Sep 17 17:59:04 CST 2022
```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

### PR DESCRIPTION
**Pull request by adofsauron**
## Summary about this PR

Issue Number: close #581 

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [x] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

File: sql/sql_optimizer.cc [hunk 1]
```diff
@@ -2935,16 +2935,35 @@ bool JOIN::get_best_combination()
...
+        {
+          delete tab->quick();
+          tab->set_quick(NULL);
+        }
       }
       else
-        // REF or RANGE, clarify later when prefix tables are set for JOIN_TABs
-        tab->set_type(JT_REF);
+      {
+        if (!pos->key)
```
Comment (RingsC) [inline sql/sql_optimizer.cc:2956]: using 
```
join_type jt_type = (tab->quick()) ? calc_join_type(tab->quick()->get_type()) : JT_ALL 
tab->set_type(JT_ALL);
```

**Review by RingsC — APPROVED** [review]

**Review by lujiashun — APPROVED** [review]
LGTM
