### PR TITLE
fix(core): rm incorrect boundary check on rough check with between #1344

### LINKED ISSUE #1344: bug: bigint boundary value problem
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```shell
mysql> create table t1 (
    ->  value64  bigint  not null,
    ->  value32  integer          not null
    -> );
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t1 values(9223372036854775806, 1);
Query OK, 1 row affected (0.01 sec)

mysql> insert into t1 values(9223372036854775807, 2);
Query OK, 1 row affected (0.00 sec)

mysql> select * from t1;
+---------------------+---------+
| value64             | value32 |
+---------------------+---------+
| 9223372036854775806 |       1 |
| 9223372036854775807 |       2 |
+---------------------+---------+
2 rows in set (0.00 sec)

mysql> select * from t1 where value64= 9223372036854775806;
+---------------------+---------+
| value64             | value32 |
+---------------------+---------+
| 9223372036854775806 |       1 |
+---------------------+---------+
1 row in set (0.00 sec)

mysql> select * from t1 where value64= 9223372036854775807;
Empty set (0.00 sec)
```

### Expected behavior

```shell
mysql> select * from t1 where value64= 9223372036854775807;
+---------------------+---------+
| value64             | value32 |
+---------------------+---------+
| 9223372036854775807 |       2 |
+---------------------+---------+
1 row in set (0.00 sec)
```

### How To Reproduce

```sql
create table t1 (
 value64  bigint   not null,
 value32  integer          not null
);
insert into t1 values(9223372036854775806, 1);
insert into t1 values(9223372036854775807, 2);
select * from t1 where value64= 9223372036854775807;
```

### Environment

```shell
root@ub01:~# /stonedb57/install/bin/mysqld --version
/stonedb57/install/bin/mysqld  Ver 5.7.36-StoneDB-v1.0.2 for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: 0f4250589
        Last commit time: Date:   Tue Feb 21 06:09:37 2023 +0000
        Build time: Date: Wed Feb 22 17:50:51 CST 2023
root@ub01:~# cat /etc/issue
Ubuntu 20.04.5 LTS \n \l
```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

### PR DESCRIPTION
**Pull request by hustjieke**
## Summary about this PR

1. change file(tianmu_attr_exeq_rs.cpp) format from dos 2 unix

2. rm incorrect between check, actually the v1 or v2 equal to boundary is illegal and it will cause empty result when condition like `where col = PLUS_INF_64`, `where col = PLUS_INF_DBL`, `where col = MINUS_INF_DBL`:

```
common::RoughSetValue TianmuAttr::RoughCheckBetween(int pack, int64_t v1, int64_
                                                                // and then consider negation
   bool is_float = Type().IsFloat();
   auto const &dpn(get_dpn(pack));
-  if (!is_float && (v1 == common::PLUS_INF_64 || v2 == common::MINUS_INF_64)) {
-    res = common::RoughSetValue::RS_NONE;
-  } else if (is_float && (v1 == *(int64_t *)&common::PLUS_INF_DBL || v2 == *(int64_t *)&common::MINUS_INF_DBL)) {
-    res = common::RoughSetValue::RS_NONE;
-  } else if (!is_float && (v1 > dpn.max_i || v2 < dpn.min_i)) {
+  if (!is_float && (v1 > dpn.max_i || v2 < dpn.min_i)) {
```

Issue Number: close #1344

## Tests Check List

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [x] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Review by duanfuxiang0 — APPROVED** [review]
LGTM

File: storage/tianmu/core/tianmu_attr_exeq_rs.cpp [hunk 1]
```diff
@@ -1,1069 +1,1071 @@
...
+  }
+  if (span != -1) {
+    int64_t tmp_min = GetMinInt64();  // always a value - i_min from TianmuAttr
+    int64_t tmp_max = GetMaxInt64();
+    if (ATI::IsRealType(TypeName()))
+      span = (span / (npack - trivial_packs)) / (*(double *)(&tmp_max) - *(double *)(&tmp_min));
+    else
+      span = (span / (npack - trivial_packs)) / double(GetMaxInt64() - GetMinInt64());
+  }
+  if (auto sp = GetFilter_Hist(); sp && GetPackType() == common::PackType::INT) {
```
Comment (wisehead) [inline storage/tianmu/core/tianmu_attr_exeq_rs.cpp:963]: the diff tool doesn't work, it's not clear what code changes are made?

Comment (wisehead) [reply storage/tianmu/core/tianmu_attr_exeq_rs.cpp:963]: talked with @hustjieke , the code looks good.

**Review by wisehead — APPROVED** [review]
