### PR TITLE
fix(tianmu): AUTO_INCREMENT of the Primary Key with tianmu occurs the problem of max value about data type(#1046)

### LINKED ISSUE #1046: bug:  AUTO_INCREMENT of the Primary Key  with tianmu occurs the problem of max value about data type
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```
 CREATE TABLE `test1` (
  `a` tinyint(4) NOT NULL AUTO_INCREMENT,
  `b` char(20) DEFAULT 'default_value',
  PRIMARY KEY (`a`)
) ENGINE=TIANMU DEFAULT CHARSET=utf8mb4

```
` insert into test1 values (126,"first"),(63, "middle"),(0,"last");`

```
mysql> select * from test1;
+-----+--------+
| a   | b      |
+-----+--------+
| 126 | first  |
|  63 | middle |
| 127 | last   |
+-----+--------+
3 rows in set (2.75 sec)
```
`insert into test1 values (0,"last");`
```
mysql> select * from test1;
+------+--------+
| a    | b      |
+------+--------+
|  126 | first  |
|   63 | middle |
|  127 | last   |
| -128 | last   |
+------+--------+
4 rows in set (0.00 sec)
```

### Expected behavior

```
 CREATE TABLE `test1` (
  `a` tinyint(4) NOT NULL AUTO_INCREMENT,
  `b` char(20) DEFAULT 'default_value',
  PRIMARY KEY (`a`)
) ENGINE=TIANMU DEFAULT CHARSET=utf8mb4

```
` insert into test1 values (126,"first"),(63, "middle"),(0,"last");`

```
mysql> select * from test1;
+-----+--------+
| a   | b      |
+-----+--------+
| 126 | first  |
|  63 | middle |
| 127 | last   |
+-----+--------+
3 rows in set (2.75 sec)
```
`insert into test1 values (0,"last");`

```
mysql> insert into test1 values (0,"last");
ERROR 1062 (23000): Duplicate entry '127' for key 'PRIMARY'
```

```
mysql> select * from test1;
+------+--------+
| a    | b      |
+------+--------+
|  126 | first  |
|   63 | middle |
|  127 | last   |
+------+--------+
3 rows in set (0.00 sec)
```

### How To Reproduce

```
 CREATE TABLE `test1` (
  `a` tinyint(4) NOT NULL AUTO_INCREMENT,
  `b` char(20) DEFAULT 'default_value',
  PRIMARY KEY (`a`)
) ENGINE=TIANMU DEFAULT CHARSET=utf8mb4

```
` insert into test1 values (126,"first"),(63, "middle"),(0,"last");`

```
mysql> select * from test1;
+-----+--------+
| a   | b      |
+-----+--------+
| 126 | first  |
|  63 | middle |
| 127 | last   |
+-----+--------+
3 rows in set (2.75 sec)
```
`insert into test1 values (0,"last");`
```
mysql> select * from test1;
+------+--------+
| a    | b      |
+------+--------+
|  126 | first  |
|   63 | middle |
|  127 | last   |
| -128 | last   |
+------+--------+
4 rows in set (0.00 sec)
```

### Environment

> 
> ./build/sql/mysqld  Ver 5.7.36-StoneDB-debug for Linux on x86_64 (build-)
> build information as follow: 
>         Repository address: https://github.com/stonedb/stonedb.git:stonedb-5.7-dev
>         Branch name: stonedb-5.7-dev
>         Last commit ID: d06b384
>         Last commit time: Date:   Sun Nov 27 19:23:35 2022 +0800
>         Build time: Date: Wed Nov 30 19:20:52 CST 2022

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

### PR DESCRIPTION
**Pull request by isredstar**
## Summary about this PR

Issue Number: close #1046 

**Analysis:** When the auto-increment obtained is greater than the maximum value of the data type, the inserted data will become negative. According to the debugging analysis of the code, it is found that the auto-increment maximum value obtained is not compared with the maximum value that the type can store, so the value overflow occurs.
**Solution:** Compare the type maximum value with auto-increment value. When the auto-increment value is less than the maximum value, it can be inserted normally. When the auto-increment value is is greater than the maximum value, it will report the error of primary key conflict.
**main fix：** if auto_inc_value < max_value, return auto_inc_value else return max_value，also consider the unsigned auto_increment column and primary key conflict.

## Tests Check List

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [] New Feature
- [x] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Review by lujiashun — APPROVED** [review]
LGTM

File: storage/tianmu/core/column_type.h [hunk 1]
```diff
@@ -142,9 +142,12 @@ struct ColumnType {
   bool GetAutoInc() const { return flag[static_cast<int>(enumCT::AUTO_INC)]; }
   void SetAutoInc(bool inc) { flag[static_cast<int>(enumCT::AUTO_INC)] = inc; }
   bool HasFilter() const { return flag[static_cast<int>(enumCT::BLOOM_FILTER)]; }
+  bool GetUnsigned() const { return m_unsigned; }
+  void SetUnsigned(bool unsigned_) { m_unsigned = unsigned_; }
 
  private:
   common::ColumnType type;
+  bool m_unsigned = false;
```
Comment (RingsC) [inline storage/tianmu/core/column_type.h]: according to our variables naming style, we do use prefix `m_` to indicates it's a class member var.  you can use `is_unsigned` or something else.

File: mysql-test/suite/tianmu/t/auto_increment.test [hunk 2]
```diff
@@ -0,0 +1,154 @@
+--source include/have_tianmu.inc
+#
+# Test auto_increment with TIANMU
+#
+
+# test auto increment
+--disable_warnings
+drop table if exists t_auto_inc;
```
Comment (RingsC) [inline mysql-test/suite/tianmu/t/auto_increment.test]: It's better to use your own database you created before the following tests start, and drop the database when test finished.

File: storage/tianmu/core/tianmu_attr.h [hunk 3]
```diff
@@ -223,9 +223,34 @@ class TianmuAttr final : public mm::TraceableObject, public PhysicalColumn, publ
   int64_t GetMaxInt64() const { return hdr.max; }
   void SetMaxInt64(int64_t a_imax) { hdr.max = a_imax; }
   bool GetIfAutoInc() const { return ct.GetAutoInc(); }
+  bool GetIfUnsigned() const { return ct.GetUnsigned(); }
   uint64_t AutoIncNext() {
     backup_auto_inc_next_ = hdr.auto_inc_next;
-    return ++hdr.auto_inc_next;
+    if (backup_auto_inc_next_ >= UINT64_MAX)
+      return backup_auto_inc_next_;
```
Comment (RingsC) [inline storage/tianmu/core/tianmu_attr.h:230]: the type of `backup_auto_inc_next_` is unsigend int 64, and its boundary is [UINT64_MIN, UINT64_MAX], and so when the if statment happens.

File: mysql-test/suite/tianmu/t/auto_increment.test [hunk 4]
```diff
@@ -0,0 +1,154 @@
...
+--error 1062
+insert into ttinyint (id, data) values (0, "last");
+select * from ttinyint;
+
+CREATE TABLE tsmallint (
+  id smallint(2) unsigned NOT NULL AUTO_INCREMENT,
+  data VARCHAR(64) DEFAULT NULL,
+  PRIMARY KEY (id)
+)  engine=tianmu;
+
```
Comment (RingsC) [inline mysql-test/suite/tianmu/t/auto_increment.test:113]: Notice that
`
When you insert any other value into an AUTO_INCREMENT column, the column is set to that value and the sequence is reset so that the next automatically generated value follows sequentially from the largest column value. For example:
`

Comment (RingsC) [reply mysql-test/suite/tianmu/t/auto_increment.test:113]: Updating an existing AUTO_INCREMENT column value also resets the AUTO_INCREMENT sequence.

Comment (RingsC) [reply mysql-test/suite/tianmu/t/auto_increment.test:113]: To start with an AUTO_INCREMENT value other than 1, set that value with [CREATE TABLE](https://dev.mysql.com/doc/refman/8.0/en/create-table.html) or [ALTER TABLE](https://dev.mysql.com/doc/refman/8.0/en/alter-table.html), like this:

For more infor, pls refer to :
https://dev.mysql.com/doc/refman/8.0/en/example-auto-increment.html

File: mysql-test/suite/tianmu/t/auto_increment.test (hunk 2 above)
Comment (isredstar) [reply mysql-test/suite/tianmu/t/auto_increment.test]: ACK, I will modify it.

File: mysql-test/suite/tianmu/t/auto_increment.test (hunk 4 above)
Comment (isredstar) [reply mysql-test/suite/tianmu/t/auto_increment.test:113]: These features of the auto increment will be added in the issue #1072 and #1059

File: storage/tianmu/core/column_type.h (hunk 1 above)
Comment (isredstar) [reply storage/tianmu/core/column_type.h]: I will modify it

File: storage/tianmu/core/tianmu_attr.h (hunk 3 above)
Comment (isredstar) [reply storage/tianmu/core/tianmu_attr.h:230]: ACK, I will modify it.

File: mysql-test/suite/tianmu/t/auto_increment.test (hunk 2 above)
Comment (isredstar) [reply mysql-test/suite/tianmu/t/auto_increment.test]: Add the following content：

```
--disable_warnings
DROP DATABASE IF EXISTS auto_increment_db;
--enable_warnings

CREATE DATABASE auto_increment_db;
USE auto_increment_db;
```

```
# Clean UP
DROP DATABASE auto_increment_db;
```

File: storage/tianmu/core/column_type.h (hunk 1 above)
Comment (isredstar) [reply storage/tianmu/core/column_type.h]: fix：
`bool is_unsigned = false;`

File: storage/tianmu/core/tianmu_attr.h (hunk 3 above)
Comment (isredstar) [reply storage/tianmu/core/tianmu_attr.h:230]: In this case we only have to deal with the upper boundary， due to  `hdr.auto_inc_next >=0`

**Review by RingsC — APPROVED** [review]
