### PR TITLE
fix(tianmu): The predicade pushdown failed lead to the table full scan (#1054)

### LINKED ISSUE #1054: bug: The predicade pushdown failed lead to the table full scan.
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```sql
[2022-12-02 09:25:04.414987] [23121] [WARN] [MYSQL:0] MSG: can_push_donw : error
[2022-12-02 09:25:04.415040] [23121] [WARN] [MYSQL:0] MSG: SELECT * FROM zz.ls_video WHERE id=15 and asset_id='WASU1535274' and bit_rate='' and duration='68' and file_name='11111111.m3u8' and file_type='' and frame_height='' and frame_rate='' and frame_width='' and hd_flag='592' and is_drm='' and md5_check_sum='' and mime_type='' and provider_id='800103' and service_type='' and TRANSFER_CONTENT_URL='' and update_num='1' and usage='' and video_id='WASU15352743' and mobaihe_id='300001229029' and store_path='/cdp/nas001/licensor/video/3000/012/29029/' and create_time='2020-06-09 13:57:13' and status='online' and update_time='2020-06-09 13:57:13'
```

### Expected behavior

_No response_

### How To Reproduce

_No response_

### Environment

./mysqld  Ver 5.7.36-StoneDB for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:HEAD
        Branch name: HEAD
        Last commit ID: 1058e3bd8
        Last commit time: Date:   Tue Nov 29 19:36:30 2022 +0800
        Build time: Date: Wed Nov 30 01:58:16 UTC 2022

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

### PR DESCRIPTION
**Pull request by konghaiya**
1. Optimize scenarios with keywords in the table.
2. Scenarios with unique constraints in the optimization table, If there is a unique constraint, only the unique constraint is used as the push down condition.
3. The optimization table contains a number or time type scenario. If there are two types, no word is used String type as pushdown condition

## Summary about this PR

Issue Number: close #1054

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [x] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

File: sql/log_event_push_cond.cc [hunk 1]
```diff
@@ -336,36 +336,94 @@ filed_str_to_sql_conditions(std::string &str_condition, const uchar *ptr,
   return 0;
 }
 
+//Check whether there are numbers or time types in the table
+static bool checklist_have_number_or_time(Field **field, uint field_num)
+{
+  for (uint col_id = 0; col_id < field_num; col_id++) {
+    Field *f = field[col_id];
```
Comment (RingsC) [inline sql/log_event_push_cond.cc:317]: Pls, add `assert` statement here, to check `field` is valid or not.

File: sql/log_event_push_cond.cc [hunk 2]
```diff
@@ -146,20 +146,20 @@ static double PowOfTen(int exponent) { return std::pow((double)10, exponent); }
...
+  @param[bool] unwanted_str               Whether string condition is required
   
   @retval   - number of bytes scanned from ptr.
 */
 static size_t
-filed_str_to_sql_conditions(std::string &str_condition, const uchar *ptr,
-                            uint type, uint meta, Field *f)
+filed_str_to_sql_conditions(std::string &str_condition, Field *f , uint meta, bool unwanted_str)
 {
+  const uchar *ptr = f->is_null() ? nullptr:f->ptr;
```
Comment (RingsC) [inline sql/log_event_push_cond.cc:159]: returns as soon as possible when ptr is nullptr.

File: mysql-test/suite/tianmu/t/issue1054.test [hunk 3]
```diff
@@ -0,0 +1,235 @@
...
+
+--echo #
+--echo # Has primary key
+--echo # 
+
+--echo [on master]
+connection master;
+
+CREATE TABLE `column_type_test` (
+`usage` tinyint(4) COMMENT 'tinyint',
```
Comment (RingsC) [inline mysql-test/suite/tianmu/t/issue1054.test:130]: Adds a test for `unicode` charset.

File: sql/log_event_push_cond.cc [hunk 4]
```diff
@@ -336,36 +336,94 @@ filed_str_to_sql_conditions(std::string &str_condition, const uchar *ptr,
...
   for (uint col_id = 0; col_id < m_table->s->fields; col_id++) {
     Field *f = field[col_id];
-    if (bitmap_is_set(cols_bitmap, col_id) == 0)
-      continue;
     uint16 meta;
     f->save_field_metadata((uchar*)&meta);
     std::string str_cond;
-    size_t size = filed_str_to_sql_conditions(str_cond, (f->is_null() ? NULL: f->ptr), f->type(), meta, f);
+
+    if(!key_field_name.empty()){
```
Comment (RingsC) [inline sql/log_event_push_cond.cc]: if `key_field_name` is null, whether we continue or not? I think this part can be refined.

File: sql/log_event_push_cond.cc [hunk 5]
```diff
@@ -336,36 +336,94 @@ filed_str_to_sql_conditions(std::string &str_condition, const uchar *ptr,
...
+          col_id = 0;
+          key_field_name = "";
+          continue;
+        }
+      }else{
+        continue;
+      }
+    }
+
+    size_t size = filed_str_to_sql_conditions(str_cond, f, meta, unwanted_str);
```
Comment (RingsC) [inline sql/log_event_push_cond.cc]: The `size` is used for what?

File: sql/log_event_push_cond.cc [hunk 6]
```diff
@@ -421,6 +479,10 @@ bool Rows_log_event::can_push_donw()
     goto error;
   thd->set_query(lex_str);
   thd->set_query_id(next_query_id());
+  DBUG_EXECUTE_IF("tianmu_can_push_down_error",
```
Comment (RingsC) [inline sql/log_event_push_cond.cc]: uses `falied` not `error`.

File: sql/log_event_push_cond.cc [hunk 7]
```diff
@@ -484,7 +546,7 @@ bool Rows_log_event::can_push_donw()
 end:
   return true; 
 error:
-  sql_print_information("can_push_donw : error");
+  sql_print_information("can_push_down : error");
```
Comment (RingsC) [inline sql/log_event_push_cond.cc]: uses `failed` not `error`.

**Review by RingsC — APPROVED** [review]

**Review by lujiashun — APPROVED** [review]
LGTM
