### PR TITLE
fix stonedb for optimize exists subquery and deep memory copy #369 (#330, #329, #340, #332)

### LINKED ISSUE #330: bug: slow-SQL-Q4-when subquery use exists sql on 10GB data spend 40 mininus and happen OOM on 100GB data
### Describe the problem

1. use tpch data
2. exec follow sql

`
select
	o_orderpriority,
	count(*) as order_count
from
	orders
where
	o_orderdate >= date '1993-07-01'
	and o_orderdate < date '1993-07-01' + interval '3' month
	and exists (
		select
			*
		from
			lineitem
		where
			l_orderkey = o_orderkey
			and l_commitdate < l_receiptdate
	)
group by
	o_orderpriority
order by
	o_orderpriority;
`

### Expected behavior

_No response_

### How To Reproduce

_No response_

### Environment

_No response_

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

### PR DESCRIPTION
**Pull request by adofsauron**
## Summary about this PR

- Code submission Repository: https://github.com/adofsauron/stonedb-dev-20220805
- Code consolidation repository: https://github.com/stoneatom/stonedb
- branch: stonedb-5.7 
-  related issuse: 
- #330 
- #329 
- #340
- #332  

## mtr测试结果:

```
[100%] shutdown_report                          [ pass ]       
--------------------------------------------------------------------------
The servers were restarted 22 times
Spent 4.815 of 218 seconds executing testcases

Check of testcase failed for: tianmu.group_concat2 tianmu.issue475 tianmu.issue469 tianmu.issue405 tianmu.truncate tianmu.issue502 tianmu.issue429 tianmu.concat tianmu.issue468 tianmu.casewhen tianmu.insert tianmu.lz4 tianmu.add_column tianmu.group_concat tianmu.orquery tianmu.issue430 tianmu.orquery1 tianmu.issue431 tianmu.issue464 tianmu.issue496 tianmu.issue467 tianmu.drop_column tianmu.issue417

Completed: All 24 tests were successful.
```

## exists子句测试结果

2825D0DA-B2BC-4152-BAD6-BB8E092837D2

subquery-Exists-paral-20220804Aug081659590831 mysql

```
/stonedb57/install/bin/mysql -D tpch -e 'select
                            o_orderpriority,
                            count(*) as order_count
                        from
                            orders
                        where
                            o_orderdate >= date '\''1993-07-01'\''
                            and o_orderdate < date '\''1993-07-01'\'' + interval '\''3'\'' month
                            and exists (
                                select
                                    *
                                from
                                    lineitem
                                where
                                    l_orderkey = o_orderkey
                                    and l_commitdate < l_receiptdate
                            )
                        group by
                            o_orderpriority
                        order by
                            o_orderpriority ;'
Warning:
PID/TID switch overriding SYSTEM
o_orderpriority	order_count
1-URGENT	114839
2-HIGH	114276
3-MEDIUM	114716
4-NOT SPECIFIED	114913
5-LOW	114927

```

## Q2子句测试

lQLPJxaQ2RwQ9jHNAb7NAb-w8aXzqpOpS80C7mKqXsBUAA_447_446

slow-q2-hash-paral-20220805Aug081659700965 mysql

Issue Number: close #330  #329 

## Tests Check List

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [x] Bug Fix
- [x] Improvement
- [x] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Review by isredstar — APPROVED** [review]
LGTM

File: storage/tianmu/core/joiner.cpp [hunk 1]
```diff
@@ -40,19 +40,34 @@ TwoDimensionalJoiner::~TwoDimensionalJoiner() {
...
+
+    if (cond[0].op == common::Operator::O_EQ) {
+      break;
+    }
+
+    if (cond[0].op == common::Operator::O_MORE_EQ || cond[0].op == common::Operator::O_MORE ||
+        cond[0].op == common::Operator::O_LESS_EQ || cond[0].op == common::Operator::O_LESS) {
+      return JoinAlgType::JTYPE_SORT;
+    }
+  } while (0);
```
Comment (RingsC) [inline storage/tianmu/core/joiner.cpp]: Why do we use do...while statment?

File: storage/tianmu/core/joiner.cpp [hunk 2]
```diff
@@ -40,19 +40,34 @@ TwoDimensionalJoiner::~TwoDimensionalJoiner() {
...
-    else
-      join_alg = JoinAlgType::JTYPE_HASH;
-  } else {
-    if (cond[0].IsType_JoinSimple() &&
-        (cond[0].op == common::Operator::O_MORE_EQ || cond[0].op == common::Operator::O_MORE ||
-         cond[0].op == common::Operator::O_LESS_EQ || cond[0].op == common::Operator::O_LESS))
-      join_alg = JoinAlgType::JTYPE_SORT;
-  }
+  do {
+    if (cond[0].IsType_Exists()) {
```
Comment (RingsC) [inline storage/tianmu/core/joiner.cpp]: Makes it more simpler.

File: storage/tianmu/core/joiner.cpp [hunk 3]
```diff
@@ -40,19 +40,34 @@ TwoDimensionalJoiner::~TwoDimensionalJoiner() {
...
+    }
+
+    if (cond[0].op == common::Operator::O_MORE_EQ || cond[0].op == common::Operator::O_MORE ||
+        cond[0].op == common::Operator::O_LESS_EQ || cond[0].op == common::Operator::O_LESS) {
+      return JoinAlgType::JTYPE_SORT;
+    }
+  } while (0);
+
+
+  JoinAlgType join_alg = JoinAlgType::JTYPE_HASH;
```
Comment (RingsC) [inline storage/tianmu/core/joiner.cpp]: seems the vars of `join_alg` is unused.

File: storage/tianmu/core/temp_table.h [hunk 4]
```diff
@@ -393,6 +396,7 @@ class TempTable : public JustATable {
   std::vector<JoinType> join_types;                 // vector of types of joins, one less than tables
   ParameterizedFilter filter;                       // multidimensional filter, contains multiindex,
                                                     // can be parametrized
+  bool filter_shallow = false;                      // is filter shallow
```
Comment (RingsC) [inline storage/tianmu/core/temp_table.h]: makes the comment on `filter_shallow` more meaningful, just like ·shallow memcpy, reduce the comsuption of mem usage.·

File: storage/tianmu/core/temp_table.h [hunk 5]
```diff
@@ -319,7 +319,10 @@ class TempTable : public JustATable {
   uint GetDisplayableAttrIndex(uint attr);
   MultiIndex *GetMultiIndexP() { return filter.mind; }
   void ClearMultiIndexP() {
-    delete filter.mind;
+    if (!filter_shallow) {
```
Comment (RingsC) [inline storage/tianmu/core/temp_table.h]: makes the `filter.mind = NULL` into `if` condition statment. otherwise, in-correcte use the function will lead memory leakage. it's not a defensive programming.

**Review by RingsC — CHANGES_REQUESTED** [review]

**Comment by adofsauron** [comment]
摘要:
记录在并行hash join时候去除DimensionGroupMultiMaterialized的深拷贝



核心函数:

DimensionGroupMultiMaterialized::Clone

```
DimensionGroup *DimensionGroupMultiMaterialized::Clone(bool shallow) {
  DimensionGroupMultiMaterialized *new_value = new DimensionGroupMultiMaterialized(no_obj, dims_used_, power_);
  if (shallow) return new_value;
  for (int index = 0; index < dims_count_; ++index) {
    MultiIndexTable *tables = dim_tables_[index];
    if (tables) {
      tables->Lock();
      new_value->dim_tables_[index] = new MultiIndexTable(*tables);
      tables->Unlock();
    }
  }
  return new_value;
}
```

优化后:

DimensionGroupMultiMaterialized::Clone

```
DimensionGroup *DimensionGroupMultiMaterialized::Clone(bool shallow) {
  DimensionGroupMultiMaterialized *new_value = new DimensionGroupMultiMaterialized(no_obj, dims_used_, power_, shallow);
  for (int index = 0; index < dims_count_; ++index) {
    MultiIndexTable *tables = dim_tables_[index];
    if (tables) {
      tables->Lock();
      if (shallow) {
        new_value->dim_tables_[index] = tables;
      } else {
        new_value->dim_tables_[index] = new MultiIndexTable(*tables);
      }

      tables->Unlock();
    }
  }
  return new_value;
}
```

DimensionGroupMultiMaterialized的析构函数

```
DimensionGroupMultiMaterialized::~DimensionGroupMultiMaterialized() {
  if (is_shallow_memory) {
    return;
  }

  for (auto it : dim_tables_) delete it;
}
```

执行测试:

dbc92944a28b2ab150a330fe558351a


slow-q18-hash-paral-20220807Aug081659863386 mysql



结论:
1. 执行结果无异常
2. 执行耗时Q18， 由6min削减为4min30s
3. 内存稳定保持在60GB (执行前后都是)

**Comment by andyli029** [comment]
Fix the commit log.

**Review by RingsC — APPROVED** [review]
