### PR TITLE
fix(stonedb8.0): fix Tianmu engine for union primary key crash (#534)

### LINKED ISSUE #534: bug: (stonedb) TPCH Q20 crashed
### Describe the problem

TPCH Q20 crash
```
#0  __GI_raise (sig=sig@entry6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6db3859 in __GI_abort =6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6db3859 in __GI_abort () at abort.c:79
#2  0x00007ffff6db3729 in __assert_fail_base (fmt=0x7ffff6f49588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0x55555c6506d8 "!table || (!table->read_set || bitmap_is_set(table->read_set, field_index()))",
    file=0x55555c650258 "/data/codebase/mysql-server-mysql-8.0.30/sql/field.cc", line=3761, function=<optimized out>) at assert.c:92
#3  0x00007ffff6dc4fd6 in __GI___assert_fail (assertion=0x55555c6506d8 "!table || (!table->read_set || bitmap_is_set(table->read_set, field_index()))",
    file=0x55555c650258 "/data/codebase/mysql-server-mysql-8.0.30/sql/field.cc", line=3761, function=0x55555c651800 "virtual longlong Field_long::val_int() const") at assert.c:101
#4  0x00005555596162a4 in Field_long::val_int (this=0x7ffa84120ae0) at /data/codebase/mysql-server-mysql-8.0.30/sql/field.cc:3761
#5  0x000055555b656cc4 in Tianmu::dbhandler::TianmuHandler::key_convert (this=0x7ffa8411e9e0, key=0x7ffa84169800 "\026\256\027", key_len=4,
    cols=std::vector of length 2, capacity 2 = {...}, keys=std::vector of length 0, capacity 0)
    at /data/codebase/mysql-server-mysql-8.0.30/storage/tianmu/handler/tianmu_handler.cpp:1571
#6  0x000055555b651086 in Tianmu::dbhandler::TianmuHandler::index_read (this=0x7ffa8411e9e0, buf=0x7ffa84120320 "\026\256\027", key=0x7ffa84169800 "\026\256\027", key_len=4,
    find_flag=HA_READ_KEY_EXACT) at /data/codebase/mysql-server-mysql-8.0.30/storage/tianmu/handler/tianmu_handler.cpp:775
#7  0x00005555596741fa in handler::index_read_map (this=0x7ffa8411e9e0, buf=0x7ffa84120320 "\026\256\027", key=0x7ffa84169800 "\026\256\027", keypart_map=1,
    find_flag=HA_READ_KEY_EXACT) at /data/codebase/mysql-server-mysql-8.0.30/sql/handler.h:5289
#8  0x000055555966010a in handler::ha_index_read_map (this=0x7ffa8411e9e0, buf=0x7ffa84120320 "\026\256\027", key=0x7ffa84169800 "\026\256\027", keypart_map=1,
    find_flag=HA_READ_KEY_EXACT) at /data/codebase/mysql-server-mysql-8.0.30/sql/handler.cc:3155
#9  0x0000555559a57e8f in RefIterator<false>::Read (this=0x7ffa8416a0e0) at /data/codebase/mysql-server-mysql-8.0.30/sql/iterators/ref_row_iterators.cc:384
#10 0x0000555559a459d7 in NestedLoopIterator::Read (this=0x7ffa8416a120) at /data/codebase/mysql-server-mysql-8.0.30/sql/iterators/composite_iterators.cc:488
#11 0x00005555593a36b3 in Query_expression::ExecuteIteratorQuery (this=0x7ffa8413c8a0, thd=0x7ffa84001040) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_union.cc:1290
#12 0x00005555593a3a3c in Query_expression::execute (this=0x7ffa8413c8a0, thd=0x7ffa84001040) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_union.cc:1343
#13 0x00005555592e7eaa in Sql_cmd_dml::execute_inner (this=0x7ffa84151730, thd=0x7ffa84001040) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_select.cc:786
#14 0x00005555592e736e in Sql_cmd_dml::execute (this=0x7ffa84151730, thd=0x7ffa84001040) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_select.cc:586
#15 0x000055555925e287 in mysql_execute_command (thd=0x7ffa84001040, first_level=true) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_parse.cc:4604
#16 0x0000555559260572 in dispatch_sql_command (thd=0x7ffa84001040, parser_state=0x7fffc848db90) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_parse.cc:5239
#17 0x0000555559255ff1 in dispatch_command (thd=0x7ffa84001040, com_data=0x7fffc848e4e0, command=COM_QUERY) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_parse.cc:1959
#18 0x0000555559254068 in do_command (thd=0x7ffa84001040) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_parse.cc:1362
#19 0x000055555949090f in handle_connection (arg=0x555560f2dcd0) at /data/codebase/mysql-server-mysql-8.0.30/sql/conn_handler/connection_handler_per_thread.cc:302
#20 0x000055555b3b266a in pfs_spawn_thread (arg=0x555563830140) at /data/codebase/mysql-server-mysql-8.0.30/storage/perfschema/pfs.cc:2942
#21 0x00007ffff7fa5609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#22 0x00007ffff6eb0133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### Expected behavior

work well，and show the correct result set.

#### 1. create table

```
CREATE TABLE `partsupp` (
  `PS_PARTKEY` tinyint  NOT NULL,
  `PS_SUPPKEY` int(11) NOT NULL,
  `PS_AVAILQTY` int(11) NOT NULL,
  `PS_SUPPLYCOST` decimal(15,2) NOT NULL,
  `PS_COMMENT` varchar(199) NOT NULL,
  PRIMARY KEY (`PS_PARTKEY`,`PS_SUPPKEY`)
) ENGINE=TIANMU DEFAULT CHARSET=utf8mb4;

CREATE TABLE `lineitem` (
  `L_ORDERKEY` int(11) NOT NULL,
  `L_PARTKEY` tinyint  NOT NULL,
  `L_SUPPKEY` int(11) NOT NULL,
  `L_LINENUMBER` int(11) NOT NULL,
  `L_QUANTITY` decimal(15,2) NOT NULL,
  `L_EXTENDEDPRICE` decimal(15,2) NOT NULL,
  `L_DISCOUNT` decimal(15,2) NOT NULL,
  `L_TAX` decimal(15,2) NOT NULL,
  `L_RETURNFLAG` char(1) NOT NULL,
  `L_LINESTATUS` char(1) NOT NULL,
  `L_SHIPDATE` date NOT NULL,
  `L_COMMITDATE` date NOT NULL,
  `L_RECEIPTDATE` date NOT NULL,
  `L_SHIPINSTRUCT` char(25) NOT NULL,
  `L_SHIPMODE` char(10) NOT NULL,
  `L_COMMENT` varchar(44) NOT NULL,
  PRIMARY KEY (`L_ORDERKEY`,`L_LINENUMBER`)
) ENGINE=TIANMU DEFAULT CHARSET=utf8mb4;
```

#### 2. insert data
```
INSERT INTO `lineitem` (`L_ORDERKEY`, `L_PARTKEY`, `L_SUPPKEY`, `L_LINENUMBER`, `L_QUANTITY`, `L_EXTENDEDPRICE`, `L_DISCOUNT`, `L_TAX`, `L_RETURNFLAG`, `L_LINESTATUS`, `L_SHIPDATE`, `L_COMMITDATE`, `L_RECEIPTDATE`, `L_SHIPINSTRUCT`, `L_SHIPMODE`, `L_COMMENT`)
VALUES
	(1, 2, 76910, 1, 17.00, 33078.94, 0.04, 0.02, 'N', 'O', '1996-03-13', '1996-02-12', '1996-03-22', 'DELIVER IN PERSON', 'TRUCK', 'egular courts above the'),
	(1, 3, 73092, 2, 36.00, 38306.16, 0.09, 0.06, 'N', 'O', '1996-04-12', '1996-02-28', '1996-04-20', 'TAKE BACK RETURN', 'MAIL', 'ly final dependencies: slyly bold '),
	(1, 4, 36999, 3, 8.00, 15479.68, 0.10, 0.02, 'N', 'O', '1996-01-29', '1996-03-05', '1996-01-31', 'TAKE BACK RETURN', 'REG AIR', 'riously. regular, express dep'),
	(1, 5, 46316, 4, 28.00, 34616.68, 0.09, 0.06, 'N', 'O', '1996-04-21', '1996-03-30', '1996-05-16', 'NONE', 'AIR', 'lites. fluffily even de'),
	(1, 6, 15274, 5, 24.00, 28974.00, 0.10, 0.04, 'N', 'O', '1996-03-30', '1996-03-14', '1996-04-01', 'NONE', 'FOB', ' pending foxes. slyly re');

INSERT INTO `partsupp` (`PS_PARTKEY`, `PS_SUPPKEY`, `PS_AVAILQTY`, `PS_SUPPLYCOST`, `PS_COMMENT`)
VALUES
	(1, 2, 3325, 771.64, ', even theodolites. regular, final theodolites eat after the carefully pending foxes. furiously regular deposits sleep slyly. carefully bold realms above the ironic dependencies haggle careful'),
	(1, 3, 8076, 993.49, 'ven ideas. quickly even packages print. pending multipliers must have to are fluff'),
	(1, 4, 3956, 337.09, 'after the fluffily ironic deposits? blithely special dependencies integrate furiously even excuses. blithely silent theodolites could have to haggle pending, express requests; fu'),
	(1, 5, 4069, 357.84, 'al, regular dependencies serve carefully after the quickly final pinto beans. furiously even deposits sleep quickly final, silent pinto beans. fluffily reg'),
	(2, 6, 8895, 378.49, 'nic accounts. final accounts sleep furiously about the ironic, bold packages. regular, regular accounts');
```

#### 3. exexute the sql(  subquery of Q20)
`select l_quantity from partsupp,lineitem where ps_partkey = l_partkey;`

### Environment

1. Linux(UBUNTU20.04/CENTOS7)
2. stonedb8.0

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

### PR DESCRIPTION
**Pull request by DandreChen**
## Summary about this PR

Issue Number: close #534 

## Tests Check List

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [x] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Review by lujiashun — APPROVED** [review]
LGTM.

File: storage/tianmu/handler/tianmu_handler.cpp [hunk 1]
```diff
@@ -1536,6 +1536,7 @@ void TianmuHandler::key_convert(const uchar *key, uint key_len, std::vector<uint
   std::vector<std::string> records;
   for (auto &i : cols) {
     Field *f = field[i];
+    bitmap_set_bit(table->read_set, f->field_index());
```
Comment (andyli029) [inline storage/tianmu/handler/tianmu_handler.cpp:1540]: Add comments.

Comment (DandreChen) [reply storage/tianmu/handler/tianmu_handler.cpp:1540]: fixed it

**Review by RingsC — APPROVED** [review]
