### PR TITLE
fix(tianmu):Resolve DDL and insert inot select Possible space inflation issues(#366) 

### LINKED ISSUE #366: bug: alter table cause engine crash
### Describe the problem

When the data volume of the table is large, such as table t_test has 19m, 2million data. When the table storage engine stonedb is changed to InnoDB, the database instance is normal. However, after the table storage engine InnoDB is changed back to tianmu, the database instance immediately crashes. The amount of data in the table is small or empty, and there is no such fault phenomenon.

#When the storage engine atomstore of the table is changed to InnoDB, the database instance is normal

alter table t_ test engine=InnoDB;

#When InnoDB, the storage engine of the table, is changed back to tianmu, the database instance will crash immediately

alter table t_ test engine=tianmu;

#Reorganize the table, that is, keep the storage engine of the table unchanged, execute the following two commands, and the database instance is normal

alter table t_ test engine=InnoDB;

alter table t_ test engine=tianmu;

According to the prompt, there may be a memory leak, but the problem remains when the private memory is reduced, such as changing the key buffer from 512M to 8m

### Expected behavior

alter table success

### How To Reproduce

1）
CREATE TABLE t_test(
  id INT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(10) NOT NULL,
  last_name VARCHAR(10) NOT NULL,
  sex VARCHAR(5) NOT NULL,
  score INT NOT NULL,
  copy_id INT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=TIANMU;

2）
DELIMITER //
    create PROCEDURE add_user(in num INT)
    BEGIN
        DECLARE rowid INT DEFAULT 0;
        DECLARE firstname CHAR(1);
        DECLARE name1 CHAR(1);
        DECLARE name2 CHAR(1);
        DECLARE lastname VARCHAR(3) DEFAULT '';
        DECLARE sex CHAR(1);
        DECLARE score CHAR(2);
        WHILE rowid < num DO
        SET firstname = SUBSTRING('赵钱孙李周吴郑王林杨柳刘孙陈江阮侯邹高彭徐',FLOOR(1+21*RAND()),1); 
        SET name1 = SUBSTRING('一二三四五六七八九十甲乙丙丁静景京晶名明铭敏闵民军君俊骏天田甜兲恬益依成城诚立莉力黎励',ROUND(1+43*RAND()),1); 
        SET name2 = SUBSTRING('一二三四五六七八九十甲乙丙丁静景京晶名明铭敏闵民军君俊骏天田甜兲恬益依成城诚立莉力黎励',ROUND(1+43*RAND()),1); 
        SET sex=FLOOR(0 + (RAND() * 2));
        SET score= FLOOR(40 + (RAND() *60));
        SET rowid = rowid + 1;
        IF ROUND(RAND())=0 THEN 
        SET lastname =name1;
        END IF;
        IF ROUND(RAND())=1 THEN
        SET lastname = CONCAT(name1,name2);
        END IF;
        insert INTO t_test (first_name,last_name,sex,score,copy_id) VALUES (firstname,lastname,sex,score,rowid);  
        END WHILE;
    END //
DELIMITER ;

3）
call add_user(2000000);

4）
alter table t_test engine=InnoDB;

5）
alter table t_test engine=tianmu;

### Environment

centos 7.9

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

### LINKED ISSUE #689: feature: insert into xxx  select * from ttt1，Poor insertion performance
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```
#It takes more than 1 hour and no result is displayed

insert into lineorder_flat SELECT `LO_ORDERDATE` , `LO_ORDERKEY` , `LO_LINENUMBER` , `LO_CUSTKEY` , `LO_PARTKEY` , `LO_SUPPKEY` , `LO_ORDERPRIORITY` , `LO_SHIPPRIORITY` , `LO_QUANTITY` , `LO_EXTENDEDPRICE` , `LO_ORDTOTALPRICE` , `LO_DISCOUNT` , `LO_REVENUE` , `LO_SUPPLYCOST` , `LO_TAX` , `LO_COMMITDATE` , `LO_SHIPMODE` , `C_NAME` , `C_ADDRESS` , `C_CITY` , `C_NATION` , `C_REGION` , `C_PHONE` , `C_MKTSEGMENT` , `S_NAME` , `S_ADDRESS` , `S_CITY` , `S_NATION` , `S_REGION` , `S_PHONE` , `P_NAME` , `P_MFGR` , `P_CATEGORY` , `P_BRAND` , `P_COLOR` , `P_TYPE` , `P_SIZE` , `P_CONTAINER` FROM (select lo_orderkey,lo_linenumber,lo_custkey,lo_partkey,lo_suppkey,lo_orderdate,lo_orderpriority,lo_shippriority,lo_quantity,lo_extendedprice,lo_ordtotalprice,lo_discount,lo_revenue,lo_supplycost,lo_tax,lo_commitdate,lo_shipmode from lineorder where lo_orderdate <19940101) l  INNER JOIN customer c ON (c.C_CUSTKEY = l.LO_CUSTKEY)  INNER JOIN supplier s ON (s.S_SUPPKEY = l.LO_SUPPKEY)  INNER JOIN part p ON  (p.P_PARTKEY = l.LO_PARTKEY);

```

### Expected behavior

Good performance, can quickly display the test results

### How To Reproduce

Write SQL similar to this syntax to see how long it takes to execute the display result

### Environment

Ver 14.14 Distrib 5.7.36_v1.0.1_beta-StoneDB

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

### LINKED ISSUE #1079: bug: INSERT INTO tbl SELECT, the table takes up a lot of disk space than INNODB
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

When using this statement ( INSERT INTO tbl SELECT ) ，the table takes up a lot of disk space than innodb

innodb :  15MB in disk space
Tianmu:  162GB in disk space

set the `tianmu_insert_delayed = OFF`
```shell
mysql>  show variables like 'tianmu_insert_delayed';
+-----------------------+-------+
| Variable_name         | Value |
+-----------------------+-------+
| tianmu_insert_delayed | OFF    |
+-----------------------+-------+
1 row in set (0.00 sec)
```

```sql
drop table if exists t;
create table t(fi int, fv varchar(30), fdt datetime);

insert into t values(1,'VAR-1',current_timestamp);
insert into t values(2,'VAR-2',current_timestamp);
insert into t values(3,'VAR-3',current_timestamp);
insert into t values(4,'VAR-4',current_timestamp);
insert into t values(5,'VAR-5',current_timestamp);
insert into t values(6,'VAR-6',current_timestamp);
insert into t values(7,'VAR-7',current_timestamp);
insert into t values(8,'VAR-8',current_timestamp);
insert into t values(9,'VAR-9',current_timestamp);
insert into t values(10,'VAR-10',current_timestamp);
select * from t;

insert into t select fi+10,concat('VAR-',fi+10),current_timestamp from t;
insert into t select fi+20,concat('VAR-',fi+20),current_timestamp from t;
insert into t select fi+40,concat('VAR-',fi+40),current_timestamp from t;
insert into t select fi+80,concat('VAR-',fi+80),current_timestamp from t;
select count(*) c from t;

insert into t select fi+160,concat('VAR-',fi+160),current_timestamp from t;
insert into t select fi+320,concat('VAR-',fi+320),current_timestamp from t;
insert into t select fi+640,concat('VAR-',fi+640),current_timestamp from t;
select count(*) c from t;

insert into t select fi+1280,concat('VAR-',fi+1280),current_timestamp from t;
insert into t select fi+2560,concat('VAR-',fi+2560),current_timestamp from t;
insert into t select fi+5120,concat('VAR-',fi+5120),current_timestamp from t;
select count(*) c from t;

insert into t select fi+10240,concat('VAR-',fi+10240),current_timestamp from t;
insert into t select fi+20480,concat('VAR-',fi+20480),current_timestamp from t;
insert into t select fi+40960,concat('VAR-',fi+40960),current_timestamp from t;
insert into t select fi+81920,concat('VAR-',fi+81920),current_timestamp from t;
insert into t select fi+163840,concat('VAR-',fi+163840),current_timestamp from t;
select count(*) c from t;
```
image

`drop table t;`

image

### Expected behavior

_No response_

### How To Reproduce

_No response_

### Environment

```shell
[root@HAST04 ~]# /stonedb57/install/bin/mysqld --version
/stonedb57/install/bin/mysqld  Ver 5.7.36-StoneDB for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: 7f69d33
        Last commit time: Date:   Tue Nov 22 06:31:04 2022 +0000
        Build time: Date: Tue Nov 22 16:53:27 CST 2022
```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

### PR DESCRIPTION
**Pull request by konghaiya**
Cause of the problem:
1. For multiple versions, Tianmu needs to first copy an original pack when performing DML operations,
Modify the copied package and use append write or overwrite write after modification
(If there is invalid space in the DATA file that can be written to the current pack, use overwrite write, otherwise use append write) to write to the file,
After the latest package is written to a file, the latest version chain will point to the address that was last written.
There is a problem with the current (TianmuAttr:: LoadData) logic. Every time you call (TianmuAttr:: LoadData),
Will write data to disk,
If there are multiple rows written in a transaction, there will be multiple copies of data,
"Because the current transaction has not been committed, the space for previous repeated writes has not been released, so the logic of overwriting writes will not be reached.",
"I only follow the logic of additional writing, which is the fundamental reason for the skyrocketing space.".
If you encounter a particularly large multiline write transaction, it will lead to a space explosion.
Moreover, disk IO is performed once per load line, which can also lead to degraded insert performance.
Solution:
To optimize the logic of (TianmuAttr:: LoadData), it is necessary to determine whether the data in the pack is full before saving changes,
Is whether to reach 65536 lines, and if so, write again,
If it cannot be reached, it is necessary to write again in the commit phase.

## Summary about this PR

Issue Number: close #366
Issue Number: close #1079
Issue Number: close #689

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [x] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

File: storage/tianmu/core/tianmu_table.cpp [hunk 1]
```diff
@@ -978,9 +978,12 @@ int TianmuTable::Insert(TABLE *table) {
       return HA_ERR_FOUND_DUPP_KEY;
     }
   }
+  utils::result_set<void> res;
   for (uint i = 0; i < NumOfAttrs(); i++) {
```
Comment (wisehead) [inline storage/tianmu/core/tianmu_table.cpp:982]: TianmuTable::Insert will be called if tianmu_sysvar_insert_delayed is OFF, and data should be inserted to disk synchronously. so using async thread to write the data is incorrect here? am i right?

**Review by wisehead — CHANGES_REQUESTED** [review]

**Review by wisehead — APPROVED** [review]

**Review by haitaoguan — APPROVED** [review]
