### PR TITLE
fix(tianmu): fix Query::Compile when happen exists subquery (#732 #301 #733)

### LINKED ISSUE #732: bug: The syntax of the exists subquery in the TIANMU layer is compiled after the rule is incorrect, and the semantics is modified
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### SQL
```sql


        select
            o_orderkey
        from
            orders
        where
            o_orderdate >= date '1993-07-01'
            and o_orderdate < date '1993-07-01' + interval '3' month
            and exists (
                select
                    *
                from
                    lineitem,orders
                where
                    l_orderkey = o_orderkey
                    and o_orderkey=6151
                limit 1
            )
        order by
            o_orderkey
        limit 10;


```

result is empty

```sql

mysql>  select
    ->             o_orderkey
    ->         from
    ->             orders
    ->         where
    ->             o_orderdate >= date '1993-07-01'
    ->             and o_orderdate < date '1993-07-01' + interval '3' month
    ->             and exists (
    ->                 select
    ->                     *
    ->                 from
    ->                     lineitem,orders
    ->                 where
    ->                     l_orderkey = o_orderkey
    ->                     and o_orderkey=6151
    ->                 limit 1
    ->             )
    ->         order by
    ->             o_orderpriority
    ->         limit 10;
Empty set (0.01 sec)


``·

### TIANMU layer syntax compiled rules
```c++

T:-1 = TABLE_ALIAS(T:0,"orders")
T:-2 = TMP_TABLE(T:4294967295)
VC:-2.0 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:0))
A:-1 = T:-2.ADD_COLUMN(VC:-2.0,LIST,"o_orderkey","ALL")
VC:-2.1 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:5))
T:-2.ADD_ORDER(VC:-2.1,ASC)
C:0 = CREATE_CONDS(T:-2,<null>,FALSE,<null>,<null>)
T:-2.ADD_CONDS(C:0,WHERE)
T:-2.APPLY_CONDS()
T:-2.MODE(LIMIT,0,10)
RESULT(T:-2)

```

### The condition in the exists subquery is directly changed to empty

```c++
C:0 = CREATE_CONDS(T:-2,<null>,FALSE,<null>,<null>)
T:-2.ADD_CONDS(C:0,WHERE)
``



### Separately execute the statement in the sub-query, the rules of the TIANMU layer are


```sql

mysql>                 select
    ->                     *
    ->                 from
    ->                     lineitem,orders
    ->                 where
    ->                     l_orderkey = o_orderkey
    ->                     and o_orderkey=6151
    ->                 limit 1\G
*************************** 1. row ***************************
     l_orderkey: 6151
      l_partkey: 27389
      l_suppkey: 7390
   l_linenumber: 1
     l_quantity: 50.00
l_extendedprice: 65819.00
     l_discount: 0.09
          l_tax: 0.03
   l_returnflag: A
   l_linestatus: F
     l_shipdate: 1993-07-22
   l_commitdate: 1993-09-27
  l_receiptdate: 1993-07-23
 l_shipinstruct: DELIVER IN PERSON
     l_shipmode: FOB
      l_comment: regular excuses alon
     o_orderkey: 6151
      o_custkey: 36995
  o_orderstatus: F
   o_totalprice: 70205.56
    o_orderdate: 1993-07-12
o_orderpriority: 1-URGENT
        o_clerk: Clerk#000000807
 o_shippriority: 0
      o_comment: s are ironically. ironic br
1 row in set (0.02 sec)


```

```c++

T:-1 = TABLE_ALIAS(T:0,"lineitem")
T:-2 = TMP_TABLE(T:-1,T:4294967293)
T:-3 = TABLE_ALIAS(T:1,"orders")
VC:-2.0 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:0))
A:-1 = T:-2.ADD_COLUMN(VC:-2.0,LIST,"l_orderkey","ALL")
VC:-2.1 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:1))
A:-2 = T:-2.ADD_COLUMN(VC:-2.1,LIST,"l_partkey","ALL")
VC:-2.2 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:2))
A:-3 = T:-2.ADD_COLUMN(VC:-2.2,LIST,"l_suppkey","ALL")
VC:-2.3 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:3))
A:-4 = T:-2.ADD_COLUMN(VC:-2.3,LIST,"l_linenumber","ALL")
VC:-2.4 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:4))
A:-5 = T:-2.ADD_COLUMN(VC:-2.4,LIST,"l_quantity","ALL")
VC:-2.5 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:5))
A:-6 = T:-2.ADD_COLUMN(VC:-2.5,LIST,"l_extendedprice","ALL")
VC:-2.6 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:6))
A:-7 = T:-2.ADD_COLUMN(VC:-2.6,LIST,"l_discount","ALL")
VC:-2.7 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:7))
A:-8 = T:-2.ADD_COLUMN(VC:-2.7,LIST,"l_tax","ALL")
VC:-2.8 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:8))
A:-9 = T:-2.ADD_COLUMN(VC:-2.8,LIST,"l_returnflag","ALL")
VC:-2.9 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:9))
A:-10 = T:-2.ADD_COLUMN(VC:-2.9,LIST,"l_linestatus","ALL")
VC:-2.10 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:10))
A:-11 = T:-2.ADD_COLUMN(VC:-2.10,LIST,"l_shipdate","ALL")
VC:-2.11 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:11))
A:-12 = T:-2.ADD_COLUMN(VC:-2.11,LIST,"l_commitdate","ALL")
VC:-2.12 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:12))
A:-13 = T:-2.ADD_COLUMN(VC:-2.12,LIST,"l_receiptdate","ALL")
VC:-2.13 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:13))
A:-14 = T:-2.ADD_COLUMN(VC:-2.13,LIST,"l_shipinstruct","ALL")
VC:-2.14 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:14))
A:-15 = T:-2.ADD_COLUMN(VC:-2.14,LIST,"l_shipmode","ALL")
VC:-2.15 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:15))
A:-16 = T:-2.ADD_COLUMN(VC:-2.15,LIST,"l_comment","ALL")
VC:-2.16 = CREATE_VC(T:-2,PHYS_COL(T:-3,A:0))
A:-17 = T:-2.ADD_COLUMN(VC:-2.16,LIST,"o_orderkey","ALL")
VC:-2.17 = CREATE_VC(T:-2,PHYS_COL(T:-3,A:1))
A:-18 = T:-2.ADD_COLUMN(VC:-2.17,LIST,"o_custkey","ALL")
VC:-2.18 = CREATE_VC(T:-2,PHYS_COL(T:-3,A:2))
A:-19 = T:-2.ADD_COLUMN(VC:-2.18,LIST,"o_orderstatus","ALL")
VC:-2.19 = CREATE_VC(T:-2,PHYS_COL(T:-3,A:3))
A:-20 = T:-2.ADD_COLUMN(VC:-2.19,LIST,"o_totalprice","ALL")
VC:-2.20 = CREATE_VC(T:-2,PHYS_COL(T:-3,A:4))
A:-21 = T:-2.ADD_COLUMN(VC:-2.20,LIST,"o_orderdate","ALL")
VC:-2.21 = CREATE_VC(T:-2,PHYS_COL(T:-3,A:5))
A:-22 = T:-2.ADD_COLUMN(VC:-2.21,LIST,"o_orderpriority","ALL")
VC:-2.22 = CREATE_VC(T:-2,PHYS_COL(T:-3,A:6))
A:-23 = T:-2.ADD_COLUMN(VC:-2.22,LIST,"o_clerk","ALL")
VC:-2.23 = CREATE_VC(T:-2,PHYS_COL(T:-3,A:7))
A:-24 = T:-2.ADD_COLUMN(VC:-2.23,LIST,"o_shippriority","ALL")
VC:-2.24 = CREATE_VC(T:-2,PHYS_COL(T:-3,A:8))
A:-25 = T:-2.ADD_COLUMN(VC:-2.24,LIST,"o_comment","ALL")
VC:-2.25 = CREATE_VC(T:-2,EXPR("6151"))
C:0 = CREATE_CONDS(T:-2,VC:-2.0,=,VC:-2.25,<null>)
C:0.AND(VC:-2.16,=,VC:-2.25,<null>)
T:-2.ADD_CONDS(C:0,WHERE)
T:-2.APPLY_CONDS()
T:-2.MODE(LIMIT,0,1)
RESULT(T:-2)


```

### Expected behavior

_No response_

### How To Reproduce

_No response_

### Environment

_No response_

### Are you interested in submitting a PR to solve the problem?

- [x] Yes, I will!

### PR DESCRIPTION
**Pull request by adofsauron**
## Summary about this PR

fix(tianmu): fix Query::Compile when happen exists subquery (#732)
The cause of an error is that you need to identify the returned 
result of the exists subquery for sl->join->zero_result_cause 
Determines whether a return value exists

Issue Number: close #732  #301 #733

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [x] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Comment by adofsauron** [comment]
The exists subquery determines whether a value exists during the query optimization phase

result is not set to zero only when a matching value is found in the query optimization phase

When a field has an index, the optimization phase scans the table through the index

The primary key implementation of the current column storage engine has a problem with the primary key index to scan the table for data

As a result, the primary key index is used to obtain the exists subquery result in the query optimization phase. Therefore, the exists subquery is not executed in the query execution phase

File: sql/sql_optimizer.cc [hunk 1]
```diff
@@ -10162,16 +10162,29 @@ static bool internal_remove_eq_conds(THD *thd, Item *cond,
...
       if (new_item == NULL)
       {
+        bool replace_always_true = false;
         if (is_cond_or)
         {
-          Item* cond_true =
-            new (thd->mem_root) Item_int((longlong)1, 1); // Always true
-          (void)li.replace(cond_true);
-          should_fix_fields = true;
+          if (dynamic_cast<Item_int*>(item))
```
Comment (RingsC) [inline sql/sql_optimizer.cc]: if (item->type() == Item::INT_ITEM) {
   convert to Item_int; then do something else. 
}
else if (item->type() == ITEM::FUNC_ITEM  {
   convert to Item_bool_func2; then do something else. otherwise,  the conversion will failed or damage the memory. 
}

Comment (RingsC) [inline sql/sql_optimizer.cc]: if (item->type() == Item::INT_ITEM) {
   convert to Item_int; then do something else. 
}
else if (item->type() == ITEM::FUNC_ITEM  {
   convert to Item_bool_func2; then do something else. otherwise,  the conversion will failed or damage the memory. 
}

File: sql/sql_optimizer.cc [hunk 2]
```diff
@@ -10162,16 +10162,29 @@ static bool internal_remove_eq_conds(THD *thd, Item *cond,
...
+            Item* left_item = args[0];
+            Item* right_item = args[1];
+            replace_always_true = left_item->eq(right_item, 0) ? true : false;
+          }
         }
-        else
-        {
-          li.remove();
+
+        if (replace_always_true)
```
Comment (RingsC) [inline sql/sql_optimizer.cc]: You should do useless clauses elimination according the comparision type. Such as. 

(A=A) AND others_clause. you can remove (A=A) because it is always true, and it will not affect the expression result.  for OR expression.  (A <>A) OR other_clauses, (A<>A) can removed due to (A<>A) is false, the OR expression result is the result of `other_clauses`.

**Review by RingsC — CHANGES_REQUESTED** [review]

File: sql/sql_optimizer.cc (hunk 1 above)
Comment (adofsauron) [reply sql/sql_optimizer.cc]: that seems good

File: sql/sql_optimizer.cc (hunk 2 above)
Comment (adofsauron) [reply sql/sql_optimizer.cc]: let me think about this

File: sql/sql_optimizer.cc (hunk 1 above)
Comment (adofsauron) [reply sql/sql_optimizer.cc]: that's good

File: sql/sql_optimizer.cc [hunk 3]
```diff
@@ -10151,8 +10151,9 @@ static bool internal_remove_eq_conds(THD *thd, Item *cond,
     *cond_value=Item::COND_UNDEF;
     Item *item;
 
-    bool is_cond_or =
-      (cond && dynamic_cast<Item_cond_or*>(cond)) ? true : false;
+    bool is_cond_or = dynamic_cast<Item_cond_or*>(cond) ? true : false;
+		bool is_cond_and = dynamic_cast<Item_cond_and*>(cond) ? true : false;
```
Comment (RingsC) [inline sql/sql_optimizer.cc]: 1:  Code alignement. 
2: For example:
const bool and_level= item_cond->functype() == Item_func::COND_AND_FUNC;

File: sql/sql_optimizer.cc [hunk 4]
```diff
@@ -10162,16 +10163,51 @@ static bool internal_remove_eq_conds(THD *thd, Item *cond,
...
         {
-          Item* cond_true =
-            new (thd->mem_root) Item_int((longlong)1, 1); // Always true
-          (void)li.replace(cond_true);
-          should_fix_fields = true;
+          Item_int* item_int = dynamic_cast<Item_int*>(item);
+          if (item_int)
+          {
+            cond_replace = true;
+						cond_value_equivalent = item_int->value ? true : false;
```
Comment (RingsC) [inline sql/sql_optimizer.cc]: 1:  Code alignment. Code format is an important thing.
2: Makes your code more consice.

**Review by RingsC — CHANGES_REQUESTED** [review]

File: sql/sql_optimizer.cc (hunk 3 above)
Comment (adofsauron) [reply sql/sql_optimizer.cc]: that's good

File: sql/sql_optimizer.cc (hunk 4 above)
Comment (adofsauron) [reply sql/sql_optimizer.cc]: that's good

File: sql/sql_optimizer.cc [hunk 5]
```diff
@@ -10144,15 +10146,17 @@ static bool internal_remove_eq_conds(THD *thd, Item *cond,
   if (cond->type() == Item::COND_ITEM)
   {
     Item_cond *const item_cond= down_cast<Item_cond *>(cond);
-    const bool and_level= item_cond->functype() == Item_func::COND_AND_FUNC;
+    const auto& item_func_type = item_cond->functype();
```
Comment (RingsC) [inline sql/sql_optimizer.cc:10163]: I think that  we just port the code from mysql 5.7 is a bettern solution. The following code is not deal with all the possible conditions. 

MySQL 5.7 code for you:
https://github.com/RingsC/mysql-server/blob/5.7/sql/sql_optimizer.cc

**Review by RingsC — DISMISSED** [review]

File: sql/sql_optimizer.cc (hunk 5 above)
Comment (adofsauron) [reply sql/sql_optimizer.cc:10163]: I think we'd better restore the sql_optimizer.cc file to the official one, the code logic being modified is too weird

Comment (adofsauron) [reply sql/sql_optimizer.cc:10163]: However, before the thorough separation of query optimization and tianmu logic, further separation is difficult to achieve

**Review by isredstar — APPROVED** [review]

**Review by lujiashun — APPROVED** [review]
LGTM
