### PR TITLE
fix(tianmu):the data is wrong when altering table after deleting.(#1199)

### LINKED ISSUE #1199: bug: (Primary/Secondary)After the character set is converted.Data on the primary database and that on the secondary database are inconsistent.
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```sql
create table ttt(id int,name varchar(5));
insert into ttt values(1,'AAA'),(2,'BBB');
alter table ttt convert to character set utf8;
delete from ttt where id=1;
alter table ttt convert to character set utf8mb4;

###MASTER
mysql> show create table ttt\G
*************************** 1. row ***************************
       Table: ttt
Create Table: CREATE TABLE `ttt` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
1 row in set (0.00 sec)

mysql> select * from ttt;
+------+------+
| id   | name |
+------+------+
|    2 | BBB  |
+------+------+
1 row in set (0.00 sec)

###SLAVE
mysql> show create table ttt\G
*************************** 1. row ***************************
       Table: ttt
Create Table: CREATE TABLE `ttt` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(5) DEFAULT NULL
) ENGINE=TIANMU DEFAULT CHARSET=utf8mb4
1 row in set (0.01 sec)

mysql> select * from ttt;
+------+------+
| id   | name |
+------+------+
| NULL | NULL |
|    2 | BBB  |
+------+------+
2 rows in set (0.00 sec)

```

### Expected behavior

```sql
mysql> select * from ttt;
+------+------+
| id   | name |
+------+------+
|    2 | BBB  |
+------+------+
1 row in set (0.00 sec)
```

### How To Reproduce

_No response_

### Environment

./mysqld  Ver 5.7.36-StoneDB for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: 0bc2cbe
        Last commit time: Date:   Fri Dec 30 17:46:55 2022 +0800
        Build time: Date: Tue Jan  3 09:59:43 CST 2023

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

### PR DESCRIPTION
**Pull request by DandreChen**
Because the records which was deleted is not filtered.

## Summary about this PR

Issue Number: close #1199 

[summary]
Because the records which was deleted is not filtered in fill_row().

## Tests Check List

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [x] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

File: storage/tianmu/handler/ha_tianmu.cpp [hunk 1]
```diff
@@ -1369,8 +1373,17 @@ int ha_tianmu::fill_row(uchar *buf) {
     std::memcpy(buffer.get(), table->record[0], table->s->reclength);
   }
 
-  for (uint col_id = 0; col_id < table->s->fields; col_id++)
-    core::Engine::ConvertToField(table->field[col_id], *(table_new_iter_.GetData(col_id)), &blob_buffers_[col_id]);
+  for (uint col_id = 0; col_id < table->s->fields; col_id++) {
+    if (core::Engine::ConvertToField(table->field[col_id], *(table_new_iter_.GetData(col_id)),
```
Comment (wisehead) [inline storage/tianmu/handler/ha_tianmu.cpp:1379]: please add some comments for this piece of code.

**Review by wisehead — CHANGES_REQUESTED** [review]

File: storage/tianmu/handler/ha_tianmu.cpp (hunk 1 above)
Comment (DandreChen) [reply storage/tianmu/handler/ha_tianmu.cpp:1379]: ack，I have fixed it.

**Review by wisehead — APPROVED** [review]

**Review by lujiashun — APPROVED** [review]
LGTM
