### PR TITLE
fix: limit unsigned integer range. #1151

### LINKED ISSUE #1151: bug: the range of unsigned should be determined
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

the range of unsigned ( INT, SMALLINT, TINYINT, MEDIUMINT, BIGINT ) should be determined,
and when INSERT the unsigned data out of range, should return the correct prompt message.

```shell
mysql> create table test(
id1 TINYINT UNSIGNED,
id2 SMALLINT UNSIGNED,
id3 INT UNSIGNED,
id4 BIGINT UNSIGNED
);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into test values(255,65535,4294967295,18446744073709551615);
Query OK, 1 row affected (0.00 sec)

mysql> insert into test values(253,65533,4294967293,18446744073709551613);
Query OK, 1 row affected (0.00 sec)

mysql> select * from test;
+------+-------+------------+----------------------+
| id1  | id2   | id3        | id4                  |
+------+-------+------------+----------------------+
|  127 | 32767 | 2147483647 | 18446744073709551615 |
|  127 | 32767 | 2147483647 | 18446744073709551613 |
+------+-------+------------+----------------------+
2 rows in set (0.00 sec)
```

### Expected behavior

```
mysql> create table test(
id1 TINYINT UNSIGNED,
id2 SMALLINT UNSIGNED,
id3 INT UNSIGNED,
id4 BIGINT UNSIGNED
);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into test values(255,65535,4294967295,18446744073709551615);
Query OK, 1 row affected (0.00 sec)

mysql> insert into test values(253,65533,4294967293,18446744073709551613);
Query OK, 1 row affected (0.00 sec)

mysql> select * from test;
+------+-------+------------+----------------------+
| id1  | id2   | id3        | id4                  |
+------+-------+------------+----------------------+
|  255 | 65535 | 4294967295 | 18446744073709551615 |
|  253 | 65533 | 4294967293 | 18446744073709551613 |
+------+-------+------------+----------------------+
2 rows in set (0.00 sec)
```

### How To Reproduce

```sql
create table test(id1 TINYINT UNSIGNED,id2 SMALLINT UNSIGNED,id3 INT UNSIGNED,id4 BIGINT UNSIGNED);
insert into test values(255,65535,4294967295,18446744073709551615);
insert into test values(253,65533,4294967293,18446744073709551613);
select * from test;
```

### Environment

```shell
root@ub01:~# /stonedb57/install/bin/mysqld --version
/stonedb57/install/bin/mysqld  Ver 5.7.36-StoneDB for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: 863cebc58
        Last commit time: Date:   Wed Dec 7 14:16:34 2022 +0800
        Build time: Date: Mon Dec 19 14:29:02 CST 2022
root@ub01:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

### PR DESCRIPTION
**Pull request by hustjieke**
## Summary about this PR

tinyint: signed range is -128 to 127, unsigned range is 0 to 127.

smallint: signed range is -32768 to 32767, unsigned range is 0 to 32767.

mediumint: signed range is -8388608 to 8388607, unsigned range is 0 to 8388607.

int/integer: signed range is -2147483647 to 2147483647, unsigned range is 0 to 2147483647. Note: -2147483648 is not allowed in tianmu engine currently.

bigint: signed range is -9223372036854775806 to 9223372036854775807, unsigned range is 0 to 9223372036854775807.
Note: -9223372036854775807 will be set to null and -9223372036854775808 will ret out of range.
Issue Number: close #1151 

## Tests Check List

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [x] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Comment by hustjieke** [comment]
Please make a CR @RingsC @wisehead @lujiashun @isredstar.

File: storage/tianmu/common/common_definitions.cpp [hunk 1]
```diff
@@ -32,6 +32,74 @@ void PushWarning(THD *thd, Sql_condition::enum_severity_level level, uint code,
   push_warning(thd, level, code, msg);
 }
 
+// Here for args int `type`, we do not use enum directly as it'll caused compiling failed for the dependent package.
```
Comment (wisehead) [inline storage/tianmu/common/common_definitions.cpp]: please add a TODO here, and change back to enum type later.

**Review by wisehead — APPROVED** [review]

File: mysql-test/suite/tianmu/t/out_of_range_issue1151.test [hunk 2]
```diff
@@ -0,0 +1,186 @@
+--source include/have_tianmu.inc
+
+drop database if exists test;
+create database test;
```
Comment (lujiashun) [inline mysql-test/suite/tianmu/t/out_of_range_issue1151.test]: Please use database such as out_of_range_issue1151 instead of test

Comment (hustjieke) [reply mysql-test/suite/tianmu/t/out_of_range_issue1151.test]: Fixed.

File: storage/tianmu/common/common_definitions.cpp (hunk 1 above)
Comment (hustjieke) [reply storage/tianmu/common/common_definitions.cpp]: OK, I had add it at the beginning of the comment.

**Comment by hustjieke** [comment]
PTAL @lujiashun

**Review by lujiashun — APPROVED** [review]
LGTM
