### PR TITLE
fix(tianmu): fix DimensionGroupVirtual clone bug when shallow is truth. (#790 #1098 #1100)

### LINKED ISSUE #790: bug: Your query contains derived queries, which results in an incorrect result set.
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

###right result
SELECT cba.branch_org_name      AS branch_org_name,
       cba.branch_org_code      AS branch_org_code,
       cba.agency_org_name      AS agency_org_name,
       cba.agency_org_code      AS agency_org_code,
       cba.customer_name        AS customer_name,
       cba.customer_code        AS customer_code,
       cba.draw_category        AS draw_category,
       cba.transfer_course      AS transfer_course,
       aa.after_account_balance AS balance
  FROM account a
  LEFT JOIN account_statement aa
    ON a.acc_id = aa.acc_id
  LEFT JOIN customer_branch_account cba
    ON a.acc_id = cba.acc_id
 INNER JOIN (SELECT MAX(id) id
               FROM account_statement
              WHERE ac_type IN (1, 2)
              GROUP BY acc_id) zd
    ON aa.id = zd.id
 WHERE a.dr = '0'
   AND aa.dr = '0'
   AND cba.dr = '0'
   AND cba.transfer_course NOT IN
       (0, 1, 20, 40, 5, 15, 32, 35, 36, 39, 42, 41, 43, 16, 31, 25)
   AND cba . type = '0'
 GROUP BY branch_org_code,
          agency_org_code,
          customer_code,
          draw_category,
          transfer_course;

###wrong result
select * from (
SELECT cba.branch_org_name      AS branch_org_name,
       cba.branch_org_code      AS branch_org_code,
       cba.agency_org_name      AS agency_org_name,
       cba.agency_org_code      AS agency_org_code,
       cba.customer_name        AS customer_name,
       cba.customer_code        AS customer_code,
       cba.draw_category        AS draw_category,
       cba.transfer_course      AS transfer_course,
       aa.after_account_balance AS balance
  FROM account a
  LEFT JOIN account_statement aa
    ON a.acc_id = aa.acc_id
  LEFT JOIN customer_branch_account cba
    ON a.acc_id = cba.acc_id
 INNER JOIN (SELECT MAX(id) id
               FROM account_statement
              WHERE ac_type IN (1, 2)
              GROUP BY acc_id) zd
    ON aa.id = zd.id
 WHERE a.dr = '0'
   AND aa.dr = '0'
   AND cba.dr = '0'
   AND cba.transfer_course NOT IN
       (0, 1, 20, 40, 5, 15, 32, 35, 36, 39, 42, 41, 43, 16, 31, 25)
   AND cba . type = '0'
 GROUP BY branch_org_code,
          agency_org_code,
          customer_code,
          draw_category,
          transfer_course
)  v;

If we set the tianmu_force_hashjoin query to on, the result will be correct. 

### Expected behavior

The tianmu_force_hashjoin will affects the execution plan but does not affect the result. 

### How To Reproduce

_No response_

### Environment

_No response_

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

### PR DESCRIPTION
**Pull request by lujiashun**
## Summary about this PR

Issue Number: close #790 #1098 #1100

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [x] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

File: storage/tianmu/core/dimension_group_virtual.cpp [hunk 1]
```diff
@@ -55,11 +55,16 @@ DimensionGroupVirtual::~DimensionGroupVirtual() {
 
 DimensionGroup *DimensionGroupVirtual::Clone(bool shallow) {
   DimensionGroupVirtual *new_value = new DimensionGroupVirtual(dims_used, base_dim, f, (shallow ? 1 : 0));
-  if (shallow)
-    return new_value;
+
   for (int i = 0; i < no_dims; i++) {
-    if (t[i]) {
-      new_value->nulls_possible[i] = nulls_possible[i];
+    if (!t[i]) {
```
Comment (RingsC) [inline storage/tianmu/core/dimension_group_virtual.cpp:62]: Would you like to add summary for this PR to describe the basic information.

**Review by RingsC — APPROVED** [review]

**Review by hustjieke — APPROVED** [review]
LGTM

**Review by isredstar — APPROVED** [review]

File: storage/tianmu/core/dimension_group_virtual.cpp (hunk 1 above)
Comment (lujiashun) [reply storage/tianmu/core/dimension_group_virtual.cpp:62]: OK, Thanks，I will add some summary.
