### PR TITLE
fix(tianmu):The mysqld is crashed when you are starting replication.(#1523)

### LINKED ISSUE #1523: bug: The mysqld is crashed when you are starting replication.
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```sql
Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7f0337fff700 (LWP 36871)]
0x00007f133e593387 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f133e593387 in raise () from /lib64/libc.so.6
#1  0x00007f133e594a78 in abort () from /lib64/libc.so.6
#2  0x00007f133e58c1a6 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007f133e58c252 in __assert_fail () from /lib64/libc.so.6
#4  0x0000000002e4c446 in Tianmu::mm::TraceableObject::~TraceableObject (this=0x7f0310000a30, __in_chrg=<optimized out>) at /home/Code/GitHub/stonedb/storage/tianmu/mm/traceable_object.cpp:131
#5  0x0000000002d9dae2 in Tianmu::core::Pack::~Pack (this=0x7f0310000a30, __in_chrg=<optimized out>) at /home/Code/GitHub/stonedb/storage/tianmu/core/pack.h:45
#6  0x0000000003096524 in Tianmu::core::PackInt::PackInt (this=0x7f0310000a30, dpn=0x7ef042201e98, pc=..., s=0x7ef272668bc0) at /home/Code/GitHub/stonedb/storage/tianmu/core/pack_int.cpp:33
#7  0x0000000002db4c18 in __gnu_cxx::new_allocator<Tianmu::core::PackInt>::construct<Tianmu::core::PackInt<Tianmu::core::DPN*&, Tianmu::core::ObjectId<(Tianmu::core::COORD_TYPE)0, 3, Tianmu::core::object_id_helper::empty> const&, Tianmu::core::ColumnShare*&> > (this=0x7f0337ffd83f, __p=0x7f0310000a30, __args#0=@0x7f0337ffda28: 0x7ef042201e98, __args#1=..., __args#2=@0x7f058c02b618: 0x7ef272668bc0) at /opt/rh/devtoolset-8/root/usr/include/c++/8/ext/new_allocator.h:136
#8  0x0000000002db371e in std::allocator_traits<std::allocator<Tianmu::core::PackInt> >::construct<Tianmu::core::PackInt<Tianmu::core::DPN*&, Tianmu::core::ObjectId<(Tianmu::core::COORD_TYPE)0, 3, Tianmu::core::object_id_helper::empty> const&, Tianmu::core::ColumnShare*&> > (__a=..., __p=0x7f0310000a30, __args#0=@0x7f0337ffda28: 0x7ef042201e98, __args#1=..., __args#2=@0x7f058c02b618: 0x7ef272668bc0)
    at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/alloc_traits.h:475
#9  0x0000000002db0eb2 in std::_Sp_counted_ptr_inplace<Tianmu::core::PackInt, std::allocator<Tianmu::core::PackInt>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<Tianmu::core::DPN*&, Tianmu::core::ObjectId<(Tianmu::core::COORD_TYPE)0, 3, Tianmu::core::object_id_helper::empty> const&, Tianmu::core::ColumnShare*&> (this=0x7f0310000a20, __a=...) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/shared_ptr_base.h:545
#10 0x0000000002dad91d in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<Tianmu::core::PackInt, std::allocator<Tianmu::core::PackInt>, Tianmu::core::DPN*&, Tianmu::core::ObjectId<(Tianmu::core::COORD_TYPE)0, 3, Tianmu::core::object_id_helper::empty> const&, Tianmu::core::ColumnShare*&> (this=0x7f0337ffda48, __p=@0x7f0337ffda40: 0x0, __a=...) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/shared_ptr_base.h:677
#11 0x0000000002da9c64 in std::__shared_ptr<Tianmu::core::PackInt, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<Tianmu::core::PackInt>, Tianmu::core::DPN*&, Tianmu::core::ObjectId<(Tianmu::core::COORD_TYPE)0, 3, Tianmu::core::object_id_helper::empty> const&, Tianmu::core::ColumnShare*&> (this=0x7f0337ffda40, __tag=...) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/shared_ptr_base.h:1342
#12 0x0000000002da70d9 in std::shared_ptr<Tianmu::core::PackInt>::shared_ptr<std::allocator<Tianmu::core::PackInt>, Tianmu::core::DPN*&, Tianmu::core::ObjectId<(Tianmu::core::COORD_TYPE)0, 3, Tianmu::core::object_id_helper::empty> const&, Tianmu::core::ColumnShare*&> (this=0x7f0337ffda40, __tag=...) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/shared_ptr.h:359
#13 0x0000000002da4b5d in std::allocate_shared<Tianmu::core::PackInt, std::allocator<Tianmu::core::PackInt>, Tianmu::core::DPN*&, Tianmu::core::ObjectId<(Tianmu::core::COORD_TYPE)0, 3, Tianmu::core::object_id_helper::empty> const&, Tianmu::core::ColumnShare*&> (__a=..., __args#0=@0x7f0337ffda28: 0x7ef042201e98, __args#1=..., __args#2=@0x7f058c02b618: 0x7ef272668bc0) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/shared_ptr.h:706
#14 0x0000000002da19ff in std::make_shared<Tianmu::core::PackInt, Tianmu::core::DPN*&, Tianmu::core::ObjectId<(Tianmu::core::COORD_TYPE)0, 3, Tianmu::core::object_id_helper::empty> const&, Tianmu::core::ColumnShare*&> (
    __args#0=@0x7f0337ffda28: 0x7ef042201e98, __args#1=..., __args#2=@0x7f058c02b618: 0x7ef272668bc0) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/shared_ptr.h:722
#15 0x0000000002d94193 in Tianmu::core::TianmuAttr::Fetch (this=0x7f058c02b480, pc=...) at /home/Code/GitHub/stonedb/storage/tianmu/core/tianmu_attr.cpp:870
#16 0x0000000002da1489 in Tianmu::core::DataCache::GetOrFetchObject<Tianmu::core::Pack, Tianmu::core::ObjectId<(Tianmu::core::COORD_TYPE)0, 3, Tianmu::core::object_id_helper::empty>, Tianmu::core::TianmuAttr> (this=0xa1a05fa0, 
    coord_=..., fetcher_=0x7f058c02b480) at /home/Code/GitHub/stonedb/storage/tianmu/core/data_cache.h:234
#17 0x0000000002d938b6 in Tianmu::core::TianmuAttr::LockPackForUse (this=0x7f058c02b480, pn=88) at /home/Code/GitHub/stonedb/storage/tianmu/core/tianmu_attr.cpp:797
#18 0x0000000002d968ba in Tianmu::core::TianmuAttr::<lambda()>::operator()(void) const (__closure=0x7f0337ffded0) at /home/Code/GitHub/stonedb/storage/tianmu/core/tianmu_attr.cpp:1200
#19 0x0000000002d9adf7 in std::_Function_handler<void(), Tianmu::core::TianmuAttr::DeleteBatchData(Tianmu::core::Transaction*, const std::vector<long unsigned int>&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/std_function.h:297
#20 0x0000000002cc4ed2 in std::function<void ()>::operator()() const (this=0x7f0337ffded0) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/std_function.h:687
#21 0x0000000002cfceb7 in Tianmu::core::FunctionExecutor::FunctionExecutor(std::function<void ()>, std::function<void ()>) (this=0x7f0337ffdd50, call_in_constructor=..., call_in_deconstructor=...)
    at /home/Code/GitHub/stonedb/storage/tianmu/core/tools.h:271
#22 0x0000000002d96be1 in Tianmu::core::TianmuAttr::DeleteBatchData (this=0x7f058c02b480, tx=0x7f058c0143f0, rows=std::vector of length 3, capacity 3 = {...}) at /home/Code/GitHub/stonedb/storage/tianmu/core/tianmu_attr.cpp:1200
#23 0x0000000002e02667 in std::__invoke_impl<void, void (Tianmu::core::TianmuAttr::*&)(Tianmu::core::Transaction*, std::vector<unsigned long, std::allocator<unsigned long> > const&), Tianmu::core::TianmuAttr<Tianmu::core::Transaction*&, std::vector<unsigned long, std::allocator<unsigned long> >&>*&> (__f=
    @0x7f058c02f2f8: (void (Tianmu::core::TianmuAttr::*)(Tianmu::core::TianmuAttr * const, Tianmu::core::Transaction *, const std::vector<unsigned long, std::allocator<unsigned long> > &)) 0x2d968e6 <Tianmu::core::TianmuAttr::DeleteBatchData(Tianmu::core::Transaction*, std::vector<unsigned long, std::allocator<unsigned long> > const&)>, __t=@0x7f058c02f328: 0x7f058c02b480, __args#0=@0x7f058c02f320: 0x7f058c0143f0, __args#1=std::vector of length 3, capacity 3 = {...})
    at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/invoke.h:73
#24 0x0000000002e01fed in std::__invoke<void (Tianmu::core::TianmuAttr::*&)(Tianmu::core::Transaction*, std::vector<unsigned long, std::allocator<unsigned long> > const&), Tianmu::core::TianmuAttr*&, Tianmu::core::Transaction*&, std::vector<unsigned long, std::allocator<unsigned long> >&> (__fn=
    @0x7f058c02f2f8: (void (Tianmu::core::TianmuAttr::*)(Tianmu::core::TianmuAttr * const, Tianmu::core::Transaction *, const std::vector<unsigned long, std::allocator<unsigned long> > &)) 0x2d968e6 <Tianmu::core::TianmuAttr::DeleteBatchData(Tianmu::core::Transaction*, std::vector<unsigned long, std::allocator<unsigned long> > const&)>, __args#0=@0x7f058c02f328: 0x7f058c02b480, __args#1=@0x7f058c02f320: 0x7f058c0143f0, 
    __args#2=std::vector of length 3, capacity 3 = {...}) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/invoke.h:95
#25 0x0000000002e01768 in std::_Bind<void (Tianmu::core::TianmuAttr::*(Tianmu::core::TianmuAttr*, Tianmu::core::Transaction*, std::vector<unsigned long, std::allocator<unsigned long> >))(Tianmu::core::Transaction*, std::vector<unsigned long, std::allocator<unsigned long> > const&)>::__call<void, , 0ul, 1ul, 2ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul>) (this=0x7f058c02f2f8, __args=empty std::tuple)
    at /opt/rh/devtoolset-8/root/usr/include/c++/8/functional:400
#26 0x0000000002dfffd8 in std::_Bind<void (Tianmu::core::TianmuAttr::*(Tianmu::core::TianmuAttr*, Tianmu::core::Transaction*, std::vector<unsigned long, std::allocator<unsigned long> >))(Tianmu::core::Transaction*, std::vector<unsigned ---Type <return> to continue, or q <return> to quit---
```

### Expected behavior

_No response_

### How To Reproduce

_No response_

### Environment

./mysqld  Ver 5.7.36-StoneDB-v1.0.3 for Linux on x86_64 (build-)
build information as follow: 
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: 4bd09ac
        Last commit time: Date:   Fri Mar 31 09:43:11 2023 +0800
        Build time: Date: Fri Mar 31 14:02:13 CST 2023

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

### PR DESCRIPTION
**Pull request by konghaiya**
It is possible to update null values with null values in the delta layer, For example:
update t set name="xiaohua" where id=1;
update t set name=null where id=1;
So when encountering this situation, directly return

## Summary about this PR

Issue Number: close #1523

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [x] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Review by haitaoguan — APPROVED** [review]

File: storage/tianmu/core/tianmu_attr.cpp [hunk 1]
```diff
@@ -1102,15 +1099,12 @@ void TianmuAttr::UpdateBatchData(core::Transaction *tx, const std::unordered_map
...
-    if (dpn.Trivial()) {
-      ha_tianmu_engine_->cache.GetOrFetchObject<Pack>(get_pc(pn), this);
-    }
 
     for (const auto &row : pack.second) {
       uint64_t row_id = row.first;
-      Value row_val = row.second;
-      if (ct.Lookup() && row_val.HasValue()) {
-        auto &str = row_val.GetString();
+      std::shared_ptr<Value> row_val = row.second;
```
Comment (wisehead) [inline storage/tianmu/core/tianmu_attr.cpp:1105]: why use shared_ptr here? please add some comments.

File: storage/tianmu/core/tianmu_attr.cpp [hunk 2]
```diff
@@ -1168,10 +1162,6 @@ void TianmuAttr::DeleteData(uint64_t row) {
   CopyPackForWrite(pn);
   auto &dpn = get_dpn(pn);
   auto dpn_save = dpn;
-  if (dpn.Trivial()) {
```
Comment (wisehead) [inline storage/tianmu/core/tianmu_attr.cpp:1171]: why remove this check?

File: storage/tianmu/core/tianmu_table.cpp [hunk 3]
```diff
@@ -209,30 +209,10 @@ class DelayedInsertParser final {
             ptr += str_len;
           } break;
           case common::PackType::INT: {
-            if (attr->Type().Lookup()) {
```
Comment (wisehead) [inline storage/tianmu/core/tianmu_table.cpp:212]: why not check the Lookup() ?

**Review by adofsauron — APPROVED** [review]
